language: generic
sudo: required

services:
    - docker

before_install:
    - docker build -t cedrikaagaard/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cedrikaagaard/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "eu-north-1"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-eu-north-1-872583650794"
    bucket_path: "docker"
    on:
        branch: main

    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
